DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 3.0
  acc_lim_y: 0
  acc_lim_th: 3.2

  max_vel_x: 0.3
  min_vel_x: -0.3
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_trans_vel: 0.3
  min_trans_vel: -0.3
  max_rot_vel: 1.0
  min_rot_vel: 0.25

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false
	
 #Trajectory Planner
TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: -0.3
  max_vel_theta: 0.3
  min_vel_theta: -0.3
  min_in_place_vel_theta: 0.3
  escape_vel: -0.1

  acc_lim_theta: 0.2
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01

  holonomic_robot: false

