controller_frequency: 10.0
recovery_behaviour_enabled: false

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 0.1
  acc_lim_y: 0
  acc_lim_theta: 0.5

  max_vel_x: 0.2
  min_vel_x: -0.2
  max_vel_y: 0
  min_vel_y: 0

  max_trans_vel: 0.2
  min_trans_vel: 0.02
  max_rot_vel: 0.1
  min_rot_vel: 0.05

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

# NavfnROS:
#   allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
#   default_tolerance: 0.1 

TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.05
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.01

  acc_lim_theta: 1.0
  acc_lim_x: 0.2
  acc_lim_y: 0.2


  holonomic_robot: false
